name: 'my_transformation'
version: '1.0.0'
config-version: 2

# This links to the credentials file we will make next
profile: 'snowflake_dbt'

# Where dbt looks for your SQL code
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Where compiled SQL goes
clean-targets: ["target", "dbt_packages"]

# Global settings for your models
# ... (rest of file) ...
models:
  my_transformation:
    # ADD THE '+' PREFIX BELOW
    +materialized: table
    +snowflake_warehouse: ELT_WH

