# This name MUST match exactly the 'profile:' name in your dbt_project.yml
snowflake_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      # --- IMPORTANT: No spaces or 'https://' in the account string ---
      account: "BKVGNQZ-UO15536"
      user: "ROSHAN"
      password: "Rosh20090798395@"
      role: "ACCOUNTADMIN"
      database: "RAW_LAKE"
      warehouse: "ELT_WH"
      schema: "ANALYTICS"
      threads: 4
      client_session_keep_alive: False
