apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      initContainers:
      - name: init-db
        image: rs121093/my-data-platform-airflow:latest
        command: ["airflow", "db", "upgrade"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@host.docker.internal:5432/airflow"
      containers:
      # --- THE WEBSERVER ---
      - name: webserver
        image: rs121093/my-data-platform-airflow:latest
        command: ["airflow", "webserver"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags
        - name: dbt-data
          mountPath: /opt/airflow/dbt_project
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@host.docker.internal:5432/airflow"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        # FIXED: Static Secret Key prevents CSRF errors on restart
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: "this_is_a_very_secure_key_for_local_dev"

      # --- THE SCHEDULER ---
      - name: scheduler
        image: rs121093/my-data-platform-airflow:latest
        command: ["airflow", "scheduler"]
        volumeMounts:
        - name: dags-data
          mountPath: /opt/airflow/dags
        - name: dbt-data
          mountPath: /opt/airflow/dbt_project
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@host.docker.internal:5432/airflow"
        # FIXED: Secret Key must match webserver
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: "this_is_a_very_secure_key_for_local_dev"

      volumes:
      - name: dags-data
        hostPath:
          path: /Users/ms/Desktop/my-data-platform/dags 
      - name: dbt-data
        hostPath:
          path: /Users/ms/Desktop/my-data-platform/dbt_project 
