version: 2

models:
  - name: stg_customers
    description: "Cleaned customer data with standardized formats."
    columns:
      - name: customer_id
        description: "Unique identifier for a customer."
        tests:
          - unique:
              config:
                severity: error
          - not_null

      - name: state
        description: "2-letter US State code."
        tests:
          - accepted_values:
              arguments:
                values: ['NY', 'CA', 'TX', 'FL']
              config:
                severity: warn

      - name: email
        tests:
          - not_null